ekf_filter_node:
  ros__parameters:

    # =========================
    # GENERAL
    # =========================
    frequency: 30.0              # 🔥 مهم للـ SLAM
    sensor_timeout: 0.1          # 🔥 مهم للـ stability

    two_d_mode: true

    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    use_sim_time: false

    # =========================
    # TIMING
    # =========================
    transform_time_offset: 0.0
    transform_timeout: 0.1       # 🔥 مهم

    # =========================
    # DEBUG
    # =========================
    print_diagnostics: true
    debug: false

    # =========================
    # ODOM INPUT
    # =========================
    odom0: /odom

    odom0_config: [
      true,  true,  false,   # x, y
      false, false, true,    # yaw
      true,  false, false,   # vx
      false, false, true,    # wz
      false, false, false
    ]

    odom0_differential: false
    odom0_relative: false

    # =========================
    # IMU INPUT
    # =========================
    imu0: /imu

    imu0_config: [
      false, false, false,   # position
      false, false, false,   # orientation (roll/pitch/yaw from imu OFF)
      false, false, false,   # linear velocity
      false, false, true,    # angular velocity (gyro z ONLY)
      false, false, false
    ]

    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true